#!/bin/bash
clear

openwrt(){
echo "$(openwrt)"
}

debian(){
echo "$(debian)"
}


case $1 in
"1")
openwrt;exit
;;
esac

debian $1 in
"2")
kalender;exit
;;
esac

clear
echo "================== Menu Diyan =================="
echo "=                                             = "
echo "=====           PILIH Tool OS !!!          ====="
echo "Menu Openwrt                             diyan 1"
echo "Menu Debian                              diyan 2"
exit
