#!/bin/bash

tanggal(){
read -p "akan menampilkan tanggal,apakah anda yakin? (y/n) : " an
if [[ $an == "y" || $an == "Y" ]]; then
echo -e "Sekarang Tanggal $(date)"
else
clear
echo -e "kembali ke halaman awal..."
exit
fi
}

kalender(){
read -p "akan menginstall xderm-mini-gui,pastikan xderm-mini sudah terinstall. apakah anda yakin? (y/n) : " an
if [[ $an == "y" || $an == "Y" ]]; then
echo -e "Menampilkan Kalender $(cal)"
else
clear
echo -e "kembali ke halaman awal..."
exit
fi
}

case $1 in
"1")
tanggal;exit
;;
esac

case $1 in
"2")
kalender;exit
;;
esac


clear
echo "====================Menu Diyan ==================== "
echo "=                                       = "
echo "===== PILIH SALAH SATU TOOLS DIINGINKAN!!! ====="
echo "DAFTAR PERINTAH :
echo "Menampilkan Tanggal                          diyan 1"
echo "Menampilkan Kalender                         diyan 2"
exit
