#!/bin/bash
clear

open(){
echo "$(openwrt)"
}

deb(){
echo "$(debian)"
}


case $1 in
"1")
open;exit
;;
esac

deb $1 in
"2")
deb;exit
;;
esac

clear
echo "================== Menu Diyan =================="
echo "=                                             = "
echo "=====           PILIH Tool OS !!!          ====="
echo "Menu Openwrt                             diyan 1"
echo "Menu Debian                              diyan 2"
exit
